server {
    listen 80;

    # FRONTEND (Next.js)
    location / {
        proxy_pass http://fe:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    # handle /api (tanpa slash)
    location = /api {
        return 301 /api/;
    }

    # semua API
    location /api/ {
        proxy_pass http://web:80/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /api-be/ {
        proxy_pass http://web:80/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # (optional) Laravel langsung tanpa /api
    location /backend/ {
        proxy_pass http://web:80/;
    }
}